version: '3'  
services: 
  bind:
    image: ventz/bind 
    container_name: bind
    restart: always    
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind:/etc/bind
      - ./bind/cache/var/cache/bind   
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - web  
    labels:
      - "traefik.frontend.rule=Host:cgx.be"  
      - "traefik.docker.network=web"
      - "traefik.port=80"  
    volumes: 
      - ./code:/code
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d 

  git:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=100
      - USER_GID=100
      - DB_HOST=localhost:3306  
    networks:
      - web
      - db  
    volumes:
      - ./gitea:/data
    ports:
      - 22:22
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:git.cgx.be"
      - "traefik.port=3000"
      - "traefik.protocol=http"
    depends_on:
      - db  
  
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - 3306:3306 
    networks:
      - db  
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=P@ssw0rd
    volumes:
      - ./db:/var/lib/mysql   

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo:/data/db
      - ./mongo/dump:/dump
    command: mongod --smallfiles

  rocketchat:
    image: rocketchat/rocket.chat:latest
    container_name: rocket
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:rocket.cgx.be"
      - "traefik.port=3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - Accounts_UseDNSDomainCheck=True
      - DEPLOY_METHOD=docker
      - ROOT_URL=http://rocket.cgx.be/  
    links: 
      - mongo:mongo


networks:
  web:
    external: true
  db:
    external: false

