version: '3'  
services: 
  bind:
    image: ventz/bind 
    container_name: bind
    restart: always    
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind:/etc/bind
      - ./bind/cache/var/cache/bind   
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - web  
    labels:
      - "traefik.docker.network=web"
      - "traefik.port=80"  
    volumes: 
      - ./code:/code
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d 

  git:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    networks:
      - web  
    volumes:
      - ./gitea:/data
    ports:
      - 22:22 
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:git.cgx.be"
      - "traefik.port=3000"
      - "traefik.protocol=http"
    depends_on:
      - db  
  
  db:
    image: mariadb:10
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=P@ssw0rd
    volumes:
      - ./db:/var/lib/mysql   

networks:
  web:
    external: true

