version: '2'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command: --docker
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.frontend.rule=Host:traefik.cgx.be"
      - "traefik.port=8080" 
      - "traefik.docker=web"  
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.tomkl
      - ./acme.json:/acme.json

networks:
  web:
    external: true

