defaultEntryPoints = ["https","http"]
[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$vywjlb3s$7OpTTmO7sQS/1qhZhhBva."]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.cgx.be"
watch = true
exposedByDefault = false

[acme]
email = "gossiauxchristophe@gmail.com"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "cgx.be"
  sans = ["git.cgx.be", "traefik.cgx.be"]
